// Top-level build file where you can add configuration options common to all sub-projects/modules.
rootProject.name = "selfie-kmp"
include(":shared")
include(":features:auth")
include(":features:home")
include(":features:profile")
include(":features:chat")
include(":features:search")
include(":features:notifications")
include(":features:shop")
include(":features:settings")
include(":features:admin")
include(":platform:androidApp")
include(":platform:iosApp")
include(":platform:webApp")
include(":platform:desktopApp")
include(":libraries:selfie-ui")
include(":libraries:selfie-network")
include(":libraries:selfie-db")
include(":libraries:selfie-analytics")
include(":libraries:selfie-crypto")
include(":tools:codegen")
include(":buildSrc")
